apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-board-dpl
  labels:
    app: kanban-board-app
spec:
  selector:
    matchLabels:
      app: kanban-board-app
  replicas: 3
  template:
    metadata:
      labels:
        app: kanban-board-app
    spec:
      containers:
        - name: kanban-board-app
          image: ashutoshkrris/kanban-board
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: kanban-board-service
spec:
  type: LoadBalancer
  selector:
    app: kanban-board-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
